fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

tuto_library:
    resource: "@TutoLibraryBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
